src/www/Controllers/JobController.cs
using nTestSwarm.Application.Infrastructure.BusInfrastructure;
using nTestSwarm.Application.Queries.JobStatus;
using nTestSwarm.Models;
using System.Web.Mvc;
using System.Web.UI;

namespace nTestSwarm.Controllers
{
    public class JobController : BusController
    {
        public JobController(IBus bus) : base(bus) { }

        [OutputCache(CacheProfile = "jobstatus", Location = OutputCacheLocation.Server)]
        public ActionResult Details(long id)
        {
            return View(id);
        }

        /// <summary>
        /// Determines the last job that was run (or is running) and redirects 
        /// to the Details action for the given job.
        /// </summary>
        public ActionResult Latest()
        {
            return Query(new LatestJobStatusQuery(), 
                         r => RedirectToAction("Details", new { id = r.JobId }), 
                         ex => View("NoJob"));
        }

        // placeholder for named routes
        public ActionResult Nullo()
        {
            return View();
        }
    }
}

src/www/Controllers/RunController.cs
using nTestSwarm.Application.Infrastructure.BusInfrastructure;
using nTestSwarm.Application.Queries.RunStatus;
using System.Text;
using System.Web.Mvc;

namespace nTestSwarm.Controllers
{
    public class RunController : BusController
    {
        public RunController(IBus bus) : base(bus) { }

        public ActionResult Status(RunStatusQuery input)
        {
            return Query(input, r => Content(r.Results, "text/html", Encoding.UTF8));
        }
    }
}

src/www/Controllers/UserAgentController.cs
using nTestSwarm.Application.Infrastructure.BusInfrastructure;
using nTestSwarm.Application.Queries.UserAgentInfo;
using System.Web.Mvc;

namespace nTestSwarm.Controllers
{
    public class UserAgentController : BusController
    {
        public UserAgentController(IBus bus) : base(bus) { }

        public ActionResult UserAgentInfo(UserAgentInfoQuery input)
        {
            return Query(input, PartialView);
        }
    }
}

src/www/Views/Job/DescribeNew.cshtml
<h2>Queue New Run</h2>

@using (Html.BeginForm("DescribeNew", "Job", FormMethod.Post, new { @class = "form-horizontal" })) {
   <div class="control-group">
       <label for="url" class="control-label">URL</label> 
       <div class="controls">
           <input type="text" id="url" name="url" />
       </div>
   </div>
    
    <div class="control-group">
        <label for="correlation" class="control-label">Correlation</label>
        <div class="controls">
            <input type="text" id="correlation" name="correlation" />
        </div>
    </div>

    <div class="control-group">
        <label for="maxruns" class="control-label">Max Runs</label>
        <div class="controls">
            <input type="text" id="maxruns" name="maxruns" />
        </div>
    </div>

    <div class="control-group">
        <div class="controls"><input type="submit" value="Queue" /></div>
    </div>
}

src/www/Views/Job/Details.cshtml
@model long
@{
    ViewBag.Title = "Job Details";
}

<h3 data-bind="text: jobName">&nbsp;</h3>

<input type="hidden" id="imagesPath" value="~/Content/images/" />
<input type="hidden" id="jobId" value="@Model" />

<table class="job-results">
    <thead>
        <tr>
            <th></th>
            <!-- ko foreach: browsers -->
            <th>
                <div class="browser">
                    <img data-bind="attr: iconAttributes" class="browser-icon" />
                    <div data-bind="text: name" class="browser-name"></div>
                </div>
            </th>
            <!-- /ko -->
        </tr>
    </thead>
    <tbody data-bind="foreach: runResults">
        <tr>
            <th><a data-bind="text: runName, attr: { href: runUrl }"></a></th>

            <!-- ko foreach: browsers -->
            <td data-bind="attr: { class: statusClass }"><a data-bind="text: statusText, attr: { href: statusUrl }"></a></td>
            <!-- /ko -->
        </tr>
    </tbody>
</table>

@section Scripts {
    <script src="~/signalr/hubs" type="text/javascript"></script>
    <script src="~/scripts/app/job-status.js" type="text/javascript"></script>
}

src/www/Views/Job/NoJob.cshtml
<h3>Job Status</h3>         

<div>No jobs exist in the system.</div>

src/www/Views/Job/StatusTable.cshtml
@using nTestSwarm.Application.Queries.JobStatus
@model JobStatusResult

<table class="job-results">
    <thead>
        <tr>
            <th></th>
            @foreach (var browser in Model.Browsers) {
            <th>
                <div class="browser" rel="@Url.Action("UserAgentInfo", "UserAgent", new {browser.Id})">
                    <img src="@(Url.Content("~/images/") + browser.Browser + ".sm.png")" class="browser-icon @browser.Browser" alt="@browser.Name" title="@browser.Name" /><br />
                    <span class="browser-name">@browser.Name</span>
                </div>
            </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var row in Model.RunResults) {
        <tr>
            <th><a href="@row.RunUrl">@row.RunName</a></th>
            @foreach (var cell in row.Cells) {
            <td class="@cell.Status.Css">
                <a href="@Url.Action("Status", "Run", new {cell.ClientId, row.RunId})">@cell.CellContents</a>
            </td>
            }
        </tr>
        }
    </tbody>
</table>