src/www/Areas/Api/Controllers/ProgramController.cs
using BootstrapSupport;
using nTestSwarm.Application;
using nTestSwarm.Application.Commands.JobQueueing;
using nTestSwarm.Application.Commands.ProgramCreation;
using nTestSwarm.Application.Commands.ProgramUpdate;
using nTestSwarm.Application.Infrastructure.BusInfrastructure;
using nTestSwarm.Application.Queries.GetProgram;
using nTestSwarm.Application.Queries.GetProgramDescriptors;
using nTestSwarm.Application.Queries.GetProgramDetails;
using nTestSwarm.Application.Queries.LatestJobForProgram;
using nTestSwarm.Application.Queries.ProgramList;
using nTestSwarm.Application.Queries.UserAgentList;
using nTestSwarm.Areas.Api.Models;
using nTestSwarm.Filters;
using System.Linq;
using System.Web.Mvc;

namespace nTestSwarm.Areas.Api.Controllers
{
    public class ProgramController : ApiController
    {

        private readonly IBus _bus;

        public ProgramController(IBus bus)
        {
            _bus = bus;
        }

        [OutputCache(Duration=2)]
        public ActionResult Index()
        {
            return HandleBusResult(_bus.Request(new ProgramListQuery()), result => 
                View(new ProgramsViewModel { Programs = result.Data }));
        }

        public ActionResult Create()
        {
            return HandleBusResult(_bus.Request(new UserAgentQuery()), r =>
            {
                var viewModel = new ProgramViewModel  
                {
                    UserAgents = r.Data
                };

                return View(viewModel);
            });
        }

        [HttpPost]
        [MvcValidation]
        public ActionResult Create(CreateProgram command)
        {
            return HandleBusResult(_bus.Send(command), _ => RedirectToAction("Index"));
        }

        public ActionResult Details(long id)
        {
            return HandleBusResult(_bus.Request(new ProgramDetailsQuery { ProgramId = id }), 
                    r => View(r.Data));
        }

        public ActionResult Edit(int id)
        {
            var query = new ProgramQuery { ProgramId = id };

            return HandleBusResult(_bus.Request(query), result => View(result.Data));
        }

        [HttpPost]
        [MvcValidation]
        public ActionResult Edit(UpdateProgram command)
        {
            return HandleBusResult(_bus.Send(command), _ => RedirectToAction("Index"));
        }

        public ActionResult QueueJob(long? id)
        {
            return HandleBusResult(_bus.Request(new ProgramDescriptorsQuery()), r =>
            {
                var programs = r.Data.Select(x => new SelectListItem { Value = x.Id.ToString(), Text = x.Name, Selected = x.Id == id })
                                    .ToList();

                programs.Insert(0, new SelectListItem { Text = "(Select)" });

                var viewModel = new QueueJobForProgramViewModel 
                {
                    ProgramId = id ?? 0,
                    Programs = programs
                };

                return View(viewModel);
            });
        }

        [HttpPost]
        public ActionResult QueueJob(QueueJobForProgram command)
        {
            if (ModelState.IsValid)
            {
                return HandleBusResult(_bus.Request(command), result =>
                {
                    if (result.Data.HasErrors)
                    {
                        TempData.Add(Alerts.ERROR,
                                     string.Join("<br/>", result.Data.Errors.Select(e => e.Value)));

                        return RedirectToAction("QueueJob");
                    }
                    else
                    {
                        //TODO: verify redirect
                        return RedirectToAction("Index");
                    }
                });
            }
            else
            {
                return QueueJob((long?)null);
            }
        }

        public ActionResult LatestJob(int id)
        {
            var query = new LatestJobForProgramQuery { ProgramId = id };

            return HandleBusResult(_bus.Request(query), r => View(r.Data));
        }

    }
}

src/www/Controllers/ProgramController.cs
using nTestSwarm.Application;
using nTestSwarm.Application.Commands.JobQueueing;
using nTestSwarm.Application.Commands.ProgramCreation;
using nTestSwarm.Application.Commands.ProgramUpdate;
using nTestSwarm.Application.Infrastructure.BusInfrastructure;
using nTestSwarm.Application.Queries;
using nTestSwarm.Application.Queries.GetProgram;
using nTestSwarm.Application.Queries.GetProgramDescriptors;
using nTestSwarm.Application.Queries.GetProgramDetails;
using nTestSwarm.Application.Queries.LatestJobForProgram;
using nTestSwarm.Application.Queries.ProgramList;
using nTestSwarm.Application.Queries.UserAgentList;
using nTestSwarm.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace nTestSwarm.Controllers
{
    public class ProgramController : BusController
    {
        public ProgramController(IBus bus) : base(bus) { }

        [OutputCache(Duration=2)]
        public ActionResult Index()
        {
            return Query(new ProgramListQuery(), null, ex => View(new ProgramListResult[0]));
        }

        public ActionResult Create()
        {
            return Query(new UserAgentQuery(), userAgents => View(new ProgramViewModel(userAgents)));
        }

        [HttpPost]
        public ActionResult Create(CreateProgram command)
        {
            if (ModelState.IsValid)
                return Send(command, () => RedirectToAction("Index"));
            else
                return Query(new UserAgentQuery(), userAgents => View(ToViewModel(command, userAgents)));
        }

        public ActionResult Details(long id)
        {
            return Query(new ProgramDetailsQuery { ProgramId = id });
        }

        public ActionResult Edit(long id)
        {
            return Query(new ProgramQuery(id));
        }

        [HttpPost]
        public ActionResult Edit(UpdateProgram command)
        {
            if (ModelState.IsValid)
                return Send(command, () => RedirectToAction("Index"));
            else
                return Query(new ProgramQuery(command.ProgramId), viewModel => View(ToViewModel(command, viewModel)));
        }

        public ActionResult QueueJob(long? id)
        {
            return Query(new ProgramDescriptorsQuery(), 
                         r => View(new QueueJobForProgramViewModel(id ?? 0, r)));
        }

        [HttpPost]
        public ActionResult QueueJob(QueueJobForProgram command)
        {
            if (ModelState.IsValid)
            {
                return Query(command, result =>
                {
                    if (result.HasErrors)
                    {
                        Errors(result.Errors.Select(e => e.Value));
                        
                        return RedirectToAction("QueueJob");
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }
                });
            }
            else
            {
                return QueueJob((long?)null);
            }
        }

        public ActionResult LatestJob(int id)
        {
            return Query(new LatestJobForProgramQuery(id), 
                         jobId => {
                             if (jobId > 0)
                                return RedirectToAction("Details", "Job", new { id = jobId });
                             else 
                                return View("NoJob"); 
                         });
        }


        private ProgramViewModel ToViewModel(CreateProgram command, IEnumerable<Descriptor> userAgents)
        {
            userAgents.SelectedBy(command.UserAgentIds);

            var viewModel = new ProgramViewModel(userAgents)
            {
                Name = command.Name,
                JobDescriptionUrl = command.JobDescriptionUrl,
                DefaultMaxRuns = command.DefaultMaxRuns
            };

            return viewModel;
        }

        private ProgramViewModel ToViewModel(UpdateProgram command, ProgramViewModel viewModel)
        {
            viewModel.Name = command.Name;
            viewModel.JobDescriptionUrl = command.JobDescriptionUrl;
            viewModel.DefaultMaxRuns = command.DefaultMaxRuns;
            viewModel.UserAgentListItems
                        .ClearSelections()
                        .SelectedBy(command.UserAgentIds);

            return viewModel;
        }
    }
}

src/www/Views/Program/Create.cshtml
@model nTestSwarm.Application.Queries.GetProgram.ProgramViewModel
@{
    ViewBag.Title = "Create Program";
    Html.EnableClientValidation();
}

<h2>Create Program</h2>

@Html.Partial("~/Views/Shared/_validationSummary.cshtml")

@using (Html.BeginForm("Create", "Program", FormMethod.Post, new { @class = "form-horizontal" })) {
    @Html.EditorFor(x => x)
    
    <div class="control-group">
        <div class="controls"><input type="submit" value="Save" class="save-button" /></div>
    </div>
}

src/www/Views/Program/Details.cshtml
@using nTestSwarm.Application
@model nTestSwarm.Application.Queries.GetProgramDetails.ProgramDetailsViewModel
@{
    ViewBag.Title = "Program - " + Model.Name;
}

<div id="program-details" class="read-only-form">
    <div id="program-panel" class="panel">
        <h3>Program Details</h3>
        <div class="row">
            <div class="display-label">Name</div>
            <div class="display-values">@Model.Name</div>
        </div>
        <div class="row">
            <div class="display-label">JobId Desc Url</div>
            <div class="display-values">@Model.JobDescriptionUrl</div>
        </div>
        <div class="row">
            <div class="display-label">Default Max Runs</div>
            <div class="display-values">@Model.DefaultMaxRuns</div>
        </div>
        <div class="row">
            <div class="display-label">User Agents</div>
            <div class="display-values">@Html.StringList(Model.UserAgents)</div>
        </div>
    </div>
    <div id="job-status-panel" class="panel">
        <h3>Last Job</h3>
        @if (Model.LastJob == null) {
        <div>This program has no jobs.</div>
        } else {
        <div class="row">
            <div class="display-label">Status</div>
            <div class="display-values">@Model.LastJob.Status</div>
        </div>
        <div class="row">
            <div class="display-label">Correlation</div>
            <div class="display-values">@Model.LastJob.Correlation</div>
        </div>
        <div class="row">
            <div class="display-label">Created</div>
            <div class="display-values">@Model.LastJob.Created</div>
        </div>
        <div class="row">
            <div class="display-label">Result</div>
            <div class="display-values">@Model.LastJobResult</div>
        </div>
        }
    </div>
</div>
<div>
    @Html.ActionLink("Edit", "edit", new { id = Model.ProgramId }, new { @class = "action-button" })
    @Html.ActionLink("Queue Job", "queuejob", new { id = Model.ProgramId }, new { @class = "action-button" })
</div>

src/www/Views/Program/Edit.cshtml
@model nTestSwarm.Application.Queries.GetProgram.ProgramViewModel
@{
    ViewBag.Title = "Edit Program";
    Html.EnableClientValidation();
}

<h2>Edit Program</h2>

@Html.Partial("~/Views/Shared/_validationSummary.cshtml")

@using (Html.BeginForm("edit", "program", new { area = "api" }, FormMethod.Post, new { @class = "form-horizontal" })) {
    @Html.HiddenFor(x => x.ProgramId)
    @Html.EditorFor(x => x)
    
    <div class="control-group">
        <div class="controls"><input type="submit" value="Save" class="save-button" /></div>
    </div>
}

src/www/Views/Program/Index.cshtml
@using nTestSwarm
@model IEnumerable<nTestSwarm.Application.Queries.ProgramList.ProgramListResult>
@{
    ViewBag.Title = "Programs";
}

<h2>Programs</h2>

<table class="selection">
    <thead>
        <tr>
            <th>Name</th>
            <th>Jobs</th>
            <th>Most Recent Job Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var program in Model) {
        <tr data-href="@Url.Action("details", new { id = @program.Id })">
            <td>@Html.ActionLink(program.Name, "details", new { id = @program.Id })</td>
            <td>@program.JobCount</td>
            @if (program.HasJobs) {
            <td>@Html.ActionLink(program.LastJobStatusText.ReplaceNullOrWhitespace("(unknown)"), "latestjob", new { id = @program.Id })</td>
            } else {
            <td></td>    
            }
            <td>
                @using (Html.BeginForm("QueueJob", "Program", new { id = @program.Id }, FormMethod.Post, new {@class = "form-horizontal"})) {
                    <input type="hidden" name="programid" value="@program.Id"/>
                    <button class="btn btn-info btn-mini" type="submit">Queue</button>
                }
            </td>
        </tr>            
        }
    </tbody>
</table>

<div>
    <a href="~/program/create" class="action-button">Create</a>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Scripts/app/data-href-handler.js"></script>
}

src/www/Views/Program/NoJob.cshtml
<h3>Job Status</h3>         

<div>No jobs exist for this program.</div>

src/www/Views/Program/QueueJob.cshtml
@model nTestSwarm.Models.QueueJobForProgramViewModel
@{
    ViewBag.Title = "Queue Job";
    Html.EnableClientValidation();
}

<h2>Queue Job</h2>

@Html.Partial("~/Views/Shared/_validationSummary.cshtml")

@using (Html.BeginForm("QueueJob", "Program", FormMethod.Post, new { @class = "form-horizontal" })) {
    
    
    <div class="control-group">
        <label for="programId" class="control-label">Programs</label>
        <div class="controls">
            @Html.DropDownList("programId", Model.Programs)
        </div>
    </div>
        
    <div class="control-group">
        <label for="url" class="control-label">URL</label> 
        <div class="controls">
            <input type="text" id="url" name="url" />
        </div>
    </div>
    
    <div class="control-group">
        <label for="correlation" class="control-label">Correlation</label>
        <div class="controls">
            <input type="text" id="correlation" name="correlation" />
        </div>
    </div>

    <div class="control-group">
        <label for="maxruns" class="control-label">Max Runs</label>
        <div class="controls">
            <input type="text" id="maxruns" name="maxruns" />
        </div>
    </div>

    <div class="control-group">
        <div class="controls"><input type="submit" value="Queue" class="save-button" /></div>
    </div>
}